import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate } from 'react-router-dom'
import { deleteJSON, fetchJSON, postJSON, type Signal, type SignalListResp } from '../api'
import { arrow, flip, sortBy, type Sort } from '../lib/sorting'

type SignalKey =
  | 'timestamp'
  | 'auto_generated'
  | 'instrument'
  | 'direction'
  | 'entry'
  | 'atm_strategy'
  | 'risk_reward'
  | 'confidence'
  | 'verdict'
  | 'outcome'
  | 'auto_resolved'

const isAutoGenerated = (s: Signal): boolean => s.trigger === 'headless'

const isAutoResolved = (s: Signal): boolean =>
  s.outcome?.result !== undefined &&
  s.outcome?.result !== null &&
  s.outcome_suggestion?.engine === 'resolver'

const accessor = (s: Signal, k: SignalKey): unknown => {
  switch (k) {
    case 'timestamp':      return s.timestamp
    case 'auto_generated': return isAutoGenerated(s)
    case 'instrument':     return s.proposal?.instrument
    case 'direction':      return s.proposal?.direction
    case 'entry':          return s.proposal?.entry
    case 'atm_strategy':   return s.proposal?.atm_strategy ?? ''
    case 'risk_reward':    return s.proposal?.risk_reward
    case 'confidence':     return s.proposal?.confidence
    case 'verdict':        return s.journal?.verdict ?? null
    case 'outcome':        return s.outcome?.result ?? null
    case 'auto_resolved':  return isAutoResolved(s)
  }
}

const fmtTs = (ts: string) => ts.replace('T', ' ').slice(0, 19)
const fmtNum = (n: number | undefined, digits = 2) =>
  n === undefined || n === null ? '' : n.toFixed(digits)

export function SignalAnalysisPage() {
  const [sort, setSort] = useState<Sort<SignalKey>>({ key: 'timestamp', dir: 'desc' })
  const [selected, setSelected] = useState<Set<string>>(new Set())
  const navigate = useNavigate()
  const qc = useQueryClient()

  const q = useQuery<SignalListResp>({
    queryKey: ['signals'],
    queryFn: () => fetchJSON<SignalListResp>('/api/signals'),
  })

  const capture = useMutation({
    mutationFn: () => postJSON<{ signal: Signal }>('/api/signals/capture'),
    onSuccess: (data) => {
      qc.invalidateQueries({ queryKey: ['signals'] })
      if (data?.signal?.timestamp) {
        navigate(`/signals/${encodeURIComponent(data.signal.timestamp)}`)
      }
    },
  })

  const bulkDelete = useMutation({
    mutationFn: async (timestamps: string[]) => {
      await Promise.all(timestamps.map((ts) =>
        deleteJSON(`/api/signals/${encodeURIComponent(ts)}`),
      ))
    },
    onSuccess: () => {
      setSelected(new Set())
      qc.invalidateQueries({ queryKey: ['signals'] })
    },
  })

  const toggleEntryTriggered = useMutation({
    mutationFn: ({ ts, triggered }: { ts: string; triggered: boolean }) =>
      postJSON<{ entry_triggered: boolean }>(
        `/api/signals/${encodeURIComponent(ts)}/entry-triggered`,
        { triggered },
      ),
    // Optimistic update so the checkbox responds instantly.
    onMutate: async ({ ts, triggered }) => {
      await qc.cancelQueries({ queryKey: ['signals'] })
      const prev = qc.getQueryData<SignalListResp>(['signals'])
      if (prev) {
        qc.setQueryData<SignalListResp>(['signals'], {
          ...prev,
          signals: prev.signals.map((s) =>
            s.timestamp === ts ? { ...s, entry_triggered: triggered } : s,
          ),
        })
      }
      return { prev }
    },
    onError: (_err, _vars, ctx) => {
      if (ctx?.prev) qc.setQueryData(['signals'], ctx.prev)
    },
    onSettled: () => qc.invalidateQueries({ queryKey: ['signals'] }),
  })

  const signals = useMemo(() => {
    if (!q.data) return []
    return sortBy(q.data.signals, sort, accessor)
  }, [q.data, sort])

  const allVisibleTs = signals.map((s) => s.timestamp)
  const allSelected = allVisibleTs.length > 0 && allVisibleTs.every((ts) => selected.has(ts))

  const toggleOne = (ts: string) => {
    const next = new Set(selected)
    if (next.has(ts)) next.delete(ts)
    else next.add(ts)
    setSelected(next)
  }
  const toggleAll = () => {
    if (allSelected) setSelected(new Set())
    else setSelected(new Set(allVisibleTs))
  }
  const onBulkDelete = () => {
    if (selected.size === 0) return
    if (confirm(`Delete ${selected.size} signal(s)? They'll be hidden from the dashboard. (Recoverable by editing signals.jsonl.)`)) {
      bulkDelete.mutate(Array.from(selected))
    }
  }

  const Th = ({ k, children, num }: { k: SignalKey; children: React.ReactNode; num?: boolean }) => (
    <th className={num ? 'num' : ''} onClick={() => setSort(flip(sort, k))}>
      {children}
      {arrow(sort, k)}
    </th>
  )

  return (
    <div className="card">
      <div className="signals-header">
        <h2>Signal Analysis {q.data && `(${q.data.count})`}</h2>
        <button
          type="button"
          className="primary capture-btn"
          onClick={() => capture.mutate()}
          disabled={capture.isPending}
          title="Open the Windows Snipping overlay; drag a rectangle on a NinjaTrader chart"
        >
          {capture.isPending ? 'Snipping… drag a rectangle on your chart' : 'Snip & Analyze'}
        </button>
      </div>
      {capture.error && (
        <div className="error" style={{ marginBottom: 12 }}>
          {String(capture.error)}
        </div>
      )}
      {selected.size > 0 && (
        <div className="bulk-bar">
          <span>{selected.size} selected</span>
          <button type="button" onClick={() => setSelected(new Set())}>Clear</button>
          <button
            type="button"
            className="danger"
            onClick={onBulkDelete}
            disabled={bulkDelete.isPending}
          >
            {bulkDelete.isPending ? 'Deleting…' : `Delete ${selected.size} signal(s)`}
          </button>
          {bulkDelete.error && <span className="error"> {String(bulkDelete.error)}</span>}
        </div>
      )}
      {q.isLoading ? (
        <div>Loading…</div>
      ) : q.error ? (
        <div className="error">{String(q.error)}</div>
      ) : (
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th className="select-col">
                  <input
                    type="checkbox"
                    checked={allSelected}
                    onChange={toggleAll}
                    title={allSelected ? 'Deselect all' : 'Select all'}
                  />
                </th>
                <Th k="timestamp">Timestamp</Th>
                <Th k="auto_generated">Auto-gen</Th>
                <Th k="instrument">Instrument</Th>
                <Th k="direction">Direction</Th>
                <Th k="entry" num>Entry</Th>
                <Th k="atm_strategy">ATM Strategy</Th>
                <Th k="risk_reward" num>R:R</Th>
                <Th k="confidence" num>Conf</Th>
                <Th k="verdict">Verdict</Th>
                <Th k="outcome">Outcome</Th>
                <Th k="auto_resolved">Auto-res</Th>
              </tr>
            </thead>
            <tbody>
              {signals.map((s) => {
                const sugPending =
                  !!s.outcome_suggestion && !s.outcome_suggestion_dismissed
                const isSelected = selected.has(s.timestamp)
                return (
                  <tr key={s.timestamp} className={sugPending ? 'pending-suggestion' : ''}>
                    <td className="select-col">
                      <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={() => toggleOne(s.timestamp)}
                      />
                    </td>
                    <td>
                      <Link to={`/signals/${encodeURIComponent(s.timestamp)}`}>
                        {fmtTs(s.timestamp)}
                      </Link>
                    </td>
                    <td title={isAutoGenerated(s) ? 'Auto-generated by headless analyzer' : 'Manual capture (Ctrl+Shift+F)'}>
                      {isAutoGenerated(s) ? '✓' : <span className="subtle">—</span>}
                    </td>
                    <td>{s.proposal?.instrument || '—'}</td>
                    <td>{s.proposal?.direction || '—'}</td>
                    <td className="num entry-cell">
                      <input
                        type="checkbox"
                        className="entry-triggered-check"
                        checked={!!s.entry_triggered}
                        onChange={(e) =>
                          toggleEntryTriggered.mutate({
                            ts: s.timestamp,
                            triggered: e.target.checked,
                          })
                        }
                        onClick={(e) => e.stopPropagation()}
                        title={
                          s.entry_triggered
                            ? 'Entry was triggered — you took this trade. Click to un-mark.'
                            : 'Mark entry as triggered (you took this trade)'
                        }
                      />
                      {fmtNum(s.proposal?.entry, 4)}
                    </td>
                    <td title={
                      s.proposal?.atm_strategy === 'custom'
                        ? `Custom suggestion (not in your NT templates): stop=${s.proposal?.atm_stop_ticks ?? '?'}t target=${s.proposal?.atm_target_ticks ?? '?'}t`
                        : s.proposal?.atm_strategy
                          ? `stop=${s.proposal?.atm_stop_ticks ?? '?'}t target=${s.proposal?.atm_target_ticks ?? '?'}t`
                          : 'No ATM strategy on this signal (older record or LLM omitted)'
                    }>
                      {s.proposal?.atm_strategy === 'custom'
                        ? <span className="atm-custom">custom ({s.proposal?.atm_stop_ticks}t/{s.proposal?.atm_target_ticks}t)</span>
                        : s.proposal?.atm_strategy || <span className="subtle">—</span>}
                    </td>
                    <td className="num">{fmtNum(s.proposal?.risk_reward, 2)}</td>
                    <td className="num">
                      {s.proposal?.confidence !== undefined
                        ? `${(s.proposal.confidence * 100).toFixed(0)}%`
                        : ''}
                    </td>
                    <td>{s.journal?.verdict || <span className="subtle">—</span>}</td>
                    <td>{s.outcome?.result || <span className="subtle">—</span>}</td>
                    <td title={isAutoResolved(s) ? 'Outcome auto-resolved by feed.db walker' : 'Manually set or unresolved'}>
                      {isAutoResolved(s) ? '✓' : <span className="subtle">—</span>}
                    </td>
                  </tr>
                )
              })}
              {signals.length === 0 && (
                <tr>
                  <td colSpan={13} className="subtle" style={{ textAlign: 'center', padding: '20px' }}>
                    No signals yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
