import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { deleteJSON, fetchJSON, fmtPrice, type Signal, type SettingsResp, type SignalListResp } from '../api'
import { arrow, flip, sortBy, type Sort } from '../lib/sorting'
import { tradingDayFor } from '../lib/trading_day'

type SignalKey =
  | 'timestamp'
  | 'auto_generated'
  | 'model'
  | 'instrument'
  | 'direction'
  | 'entry'
  | 'entered'
  | 'atm_strategy'
  | 'risk_reward'
  | 'contracts'
  | 'outcome'
  | 'realized_pnl'
  | 'time_in_trade'
  | 'auto_resolved'
  | 'notes'

type EnteredState = 'hit' | 'no_entry' | 'pending'
const FOUR_HOURS_MS = 4 * 3600 * 1000

function enteredState(s: Signal): EnteredState {
  // Bot-side entry_resolver writes entry_triggered true/false within the 4h
  // window. While we're waiting on it (or pre-watcher signals), derive a
  // local 'pending' vs 'no_entry' fallback so the column still tells a
  // useful story before the bot catches up.
  // A flat proposal has nothing to enter -- the watcher skips flats, so they'd
  // otherwise sit 'pending' forever. Treat flat as no entry by definition.
  if (s.proposal?.direction === 'flat') return 'no_entry'
  if (s.entry_triggered === true) return 'hit'
  // The resolver only records a leg exit (with P&L) after price entered and the
  // bracket resolved -- so a resolved leg means it entered, even before
  // entry_triggered is stamped. Keeps the Entered column from showing 'pending'
  // while the P&L column already shows a number.
  if (s.legs && s.legs.some((l) => l.exit_ts != null)) return 'hit'
  if (s.entry_triggered === false) return 'no_entry'
  // Implicit: not yet resolved by watcher. Check signal age.
  const t = Date.parse(s.timestamp)
  if (isNaN(t)) return 'pending'
  return (Date.now() - t) >= FOUR_HOURS_MS ? 'no_entry' : 'pending'
}

// Contracts in the trade: prefer the computed sizing, fall back to the ATM
// template's total quantity (scale-out templates carry >1).
const contractsOf = (s: Signal): number | null =>
  s.metrics?.position_size ?? s.proposal?.atm_total_qty ?? null

// Wall-clock time the position was live: entry (entry_hit_ts, else exec fill,
// else the signal timestamp) -> last leg exit. null until we have both ends.
const timeInTradeMs = (s: Signal): number | null => {
  const exits = (s.legs ?? []).map(l => l.exit_ts).filter((t): t is number => typeof t === 'number')
  if (exits.length === 0) return null
  const exit = Math.max(...exits)
  const entry = s.entry_hit_ts
    ?? (s.exec?.filled_at ? Date.parse(s.exec.filled_at) : Date.parse(s.timestamp))
  if (!isFinite(entry) || exit <= entry) return null
  return exit - entry
}

const fmtDuration = (ms: number | null): string => {
  if (ms === null || !isFinite(ms) || ms < 0) return '—'
  const totalSec = Math.round(ms / 1000)
  if (totalSec < 60) return `${totalSec}s`
  const m = Math.floor(totalSec / 60)
  if (m < 60) return `${m}m`
  return `${Math.floor(m / 60)}h ${m % 60}m`
}

// Effective time for a signal: if it actually executed a real trade, use the
// entry-fill time (exec.filled_at), not the earlier generation timestamp -- so
// display, sorting, trading-day, and the date/time filter reflect when the trade
// really happened. Falls back to the generation ts for un-traded signals.
const tradeTs = (s: Signal): string =>
  (s.exec?.state === 'filled' && s.exec.filled_at) ? s.exec.filled_at : s.timestamp

const isAutoGenerated = (s: Signal): boolean => s.trigger === 'headless'

const isAutoResolved = (s: Signal): boolean =>
  s.outcome?.result !== undefined &&
  s.outcome?.result !== null &&
  s.outcome_suggestion?.engine === 'resolver'

const accessor = (s: Signal, k: SignalKey): unknown => {
  switch (k) {
    case 'timestamp':      return tradeTs(s)
    case 'auto_generated': return isAutoGenerated(s)
    case 'model':          return s.model ?? ''
    case 'instrument':     return s.proposal?.instrument
    case 'direction':      return s.proposal?.direction
    case 'entry':          return s.proposal?.entry
    case 'entered':        return enteredState(s)
    case 'atm_strategy':   return s.proposal?.atm_strategy ?? ''
    case 'risk_reward':    return s.proposal?.risk_reward
    case 'contracts':      return contractsOf(s)
    case 'outcome':        return s.outcome?.result ?? null
    case 'realized_pnl':   return s.metrics?.realized_pnl ?? null
    case 'time_in_trade':  return timeInTradeMs(s)
    case 'auto_resolved':  return isAutoResolved(s)
    case 'notes':          return s.journal?.note ?? null
  }
}

const fmtTs = (ts: string) => ts.replace('T', ' ').slice(0, 19)
// Compact R:R display. 1.0 -> "1:1", 2.5 -> "1:2.5", 10.0 -> "1:10".
// Avoids the wide '10.00' column that 1:10 strategies produced.
const fmtRR = (n: number | undefined): string => {
  if (n === undefined || n === null) return ''
  if (!isFinite(n) || n <= 0) return '—'
  return n >= 10 ? `1:${Math.round(n)}` : `1:${n.toFixed(1)}`
}

interface SignalKpi {
  count:        number
  resolved:     number
  pnl:          number
  wins:         number
  losses:       number
  instruments:  string[]
  autoGen:      number
  autoRes:      number
  avgRR:         number | null
}

function computeKpi(signals: Signal[]): SignalKpi {
  let pnl = 0, resolved = 0, wins = 0, losses = 0
  let autoGen = 0, autoRes = 0
  let rrSum = 0, rrN = 0
  const instruments = new Set<string>()
  for (const s of signals) {
    if (isAutoGenerated(s)) autoGen++
    if (isAutoResolved(s)) autoRes++
    const p = s.metrics?.realized_pnl
    if (typeof p === 'number') {
      pnl += p
      if (p > 0) wins++
      else if (p < 0) losses++
    }
    const res = s.outcome?.result
    if (res && res !== 'pending') resolved++
    const ins = s.proposal?.instrument
    if (ins) instruments.add(ins)
    const r = s.proposal?.risk_reward
    if (typeof r === 'number' && isFinite(r) && r > 0) { rrSum += r; rrN++ }
  }
  return {
    count:        signals.length,
    resolved,
    pnl:          Math.round(pnl * 100) / 100,
    wins,
    losses,
    instruments:  Array.from(instruments).sort(),
    autoGen,
    autoRes,
    avgRR:         rrN > 0 ? rrSum / rrN : null,
  }
}

interface SignalFilters {
  instruments: string[]            // empty == all
  dayFrom:     string              // YYYY-MM-DD trading day; empty == no lower bound
  dayTo:       string              // YYYY-MM-DD trading day; empty == no upper bound
  fromTs:      string              // datetime-local (YYYY-MM-DDTHH:MM) lower bound on the signal timestamp; empty == none
  toTs:        string              // datetime-local upper bound; empty == none
  direction:   '' | 'long' | 'short' | 'flat'
}

const EMPTY_FILTERS: SignalFilters = { instruments: [], dayFrom: '', dayTo: '', fromTs: '', toTs: '', direction: '' }

function filtersActive(f: SignalFilters): boolean {
  return f.instruments.length > 0 || !!f.dayFrom || !!f.dayTo || !!f.fromTs || !!f.toTs || !!f.direction
}

export function SignalAnalysisPage() {
  const [sort, setSort] = useState<Sort<SignalKey>>({ key: 'timestamp', dir: 'desc' })
  const [selected, setSelected] = useState<Set<string>>(new Set())
  const [filters, setFilters] = useState<SignalFilters>(EMPTY_FILTERS)
  const qc = useQueryClient()

  const q = useQuery<SignalListResp>({
    queryKey: ['signals'],
    queryFn: () => fetchJSON<SignalListResp>('/api/signals'),
  })

  const bulkDelete = useMutation({
    mutationFn: async (timestamps: string[]) => {
      await Promise.all(timestamps.map((ts) =>
        deleteJSON(`/api/signals/${encodeURIComponent(ts)}`),
      ))
    },
    onSuccess: () => {
      setSelected(new Set())
      qc.invalidateQueries({ queryKey: ['signals'] })
    },
  })

  // KPI derivation: parallel stats for the current CME session and the
  // full history. Both come from the same signal list so we don't need a
  // separate API. Session = current trading day per the operator's TZ +
  // 5 PM CT roll (matches the home.py "today" rule). Falls back to
  // America/Chicago while settings load.
  const settingsQ = useQuery({
    queryKey: ['settings'],
    queryFn:  () => fetchJSON<SettingsResp>('/api/settings'),
    staleTime: 60_000,
  })
  const tz = settingsQ.data?.settings.appearance.timezone ?? 'America/Chicago'

  // Filtered + sorted table contents. The condensed metrics strip + the table
  // both reflect this filtered set.
  const signals = useMemo(() => {
    if (!q.data) return []
    const filtered = q.data.signals.filter((s) => {
      if (filters.instruments.length > 0) {
        const ins = s.proposal?.instrument
        if (!ins || !filters.instruments.includes(ins)) return false
      }
      if (filters.direction) {
        if ((s.proposal?.direction || '').toLowerCase() !== filters.direction) return false
      }
      if (filters.dayFrom || filters.dayTo) {
        const ts = tradeTs(s)
        if (!ts) return false
        const day = tradingDayFor(new Date(ts), tz)
        if (filters.dayFrom && day < filters.dayFrom) return false
        if (filters.dayTo   && day > filters.dayTo)   return false
      }
      // Date+time range on the effective trade time (independent of the
      // trading-day filter). Both bounds parse as local time, like the timestamp.
      if (filters.fromTs || filters.toTs) {
        const t = Date.parse(tradeTs(s))
        if (isNaN(t)) return false
        if (filters.fromTs && t < Date.parse(filters.fromTs)) return false
        if (filters.toTs   && t > Date.parse(filters.toTs))   return false
      }
      return true
    })
    return sortBy(filtered, sort, accessor)
  }, [q.data, sort, filters, tz])

  // Instrument options for the filter chips -- derived from the loaded set
  // so the user can only filter by tickers they actually have. Sorted to
  // keep the chip order stable across renders.
  const knownInstruments = useMemo(() => {
    const set = new Set<string>()
    for (const s of q.data?.signals ?? []) {
      const ins = s.proposal?.instrument
      if (ins) set.add(ins)
    }
    return Array.from(set).sort()
  }, [q.data])

  // Condensed key metrics over the CURRENTLY FILTERED signals -- this strip
  // follows the filter bar (unlike the old session/all-time cards). `signals`
  // is already filtered + sorted above.
  const filteredKpi = useMemo(() => computeKpi(signals), [signals])

  const allVisibleTs = signals.map((s) => s.timestamp)
  const allSelected = allVisibleTs.length > 0 && allVisibleTs.every((ts) => selected.has(ts))

  const toggleOne = (ts: string) => {
    const next = new Set(selected)
    if (next.has(ts)) next.delete(ts)
    else next.add(ts)
    setSelected(next)
  }
  const toggleAll = () => {
    if (allSelected) setSelected(new Set())
    else setSelected(new Set(allVisibleTs))
  }
  const onBulkDelete = () => {
    if (selected.size === 0) return
    if (confirm(`Delete ${selected.size} signal(s)? They'll be hidden from the dashboard. (Recoverable by editing signals.jsonl.)`)) {
      bulkDelete.mutate(Array.from(selected))
    }
  }

  const Th = ({ k, children, num }: { k: SignalKey; children: React.ReactNode; num?: boolean }) => (
    <th className={num ? 'num' : ''} onClick={() => setSort(flip(sort, k))}>
      {children}
      {arrow(sort, k)}
    </th>
  )

  const fmtMoney = (n: number) =>
    `$${n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
  const pnlCls = (n: number) => (n > 0 ? 'pnl-pos' : n < 0 ? 'pnl-neg' : '')

  const winRate = (k: SignalKpi): string => {
    const denom = k.wins + k.losses
    return denom === 0 ? '—' : `${Math.round((k.wins / denom) * 100)}%`
  }
  const fmtRRAvg = (n: number | null): string =>
    n === null ? '—' : fmtRR(n)

  return (
    <>
    <div className="card">
      <div className="signals-header">
        <h2>
          Signal Analysis{' '}
          {q.data && (
            filtersActive(filters)
              ? <span className="subtle">({signals.length} of {q.data.count})</span>
              : <span className="subtle">({q.data.count})</span>
          )}
        </h2>
      </div>

      <SignalFilterBar
        filters={filters}
        setFilters={setFilters}
        instruments={knownInstruments}
      />

      {/* Condensed key metrics for the currently filtered signals. */}
      <div
        className="signal-metrics-strip"
        style={{ display: 'flex', flexWrap: 'wrap', gap: '4px 18px', alignItems: 'baseline', margin: '8px 0 4px' }}
      >
        <strong>{filtersActive(filters) ? 'Filtered' : 'All'} signals</strong>
        <span><strong>{filteredKpi.count}</strong> signals</span>
        <span>P&L <strong className={pnlCls(filteredKpi.pnl)}>{fmtMoney(filteredKpi.pnl)}</strong></span>
        <span>Win <strong>{winRate(filteredKpi)}</strong> <span className="subtle">({filteredKpi.wins}W / {filteredKpi.losses}L)</span></span>
        <span>Resolved <strong>{filteredKpi.resolved}/{filteredKpi.count}</strong></span>
        <span>Avg R:R <strong>{fmtRRAvg(filteredKpi.avgRR)}</strong></span>
        <span>Auto <span className="subtle">gen</span> <strong>{filteredKpi.autoGen}</strong> · <span className="subtle">res</span> <strong>{filteredKpi.autoRes}</strong></span>
        {filteredKpi.instruments.length > 0 && (
          <span className="subtle">{filteredKpi.instruments.join(', ')}</span>
        )}
      </div>

      {selected.size > 0 && (
        <div className="bulk-bar">
          <span>{selected.size} selected</span>
          <button type="button" onClick={() => setSelected(new Set())}>Clear</button>
          <button
            type="button"
            className="danger"
            onClick={onBulkDelete}
            disabled={bulkDelete.isPending}
          >
            {bulkDelete.isPending ? 'Deleting…' : `Delete ${selected.size} signal(s)`}
          </button>
          {bulkDelete.error && <span className="error"> {String(bulkDelete.error)}</span>}
        </div>
      )}
      {q.isLoading ? (
        <div>Loading…</div>
      ) : q.error ? (
        <div className="error">{String(q.error)}</div>
      ) : (
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th className="select-col">
                  <input
                    type="checkbox"
                    checked={allSelected}
                    onChange={toggleAll}
                    title={allSelected ? 'Deselect all' : 'Select all'}
                  />
                </th>
                <Th k="timestamp">Timestamp</Th>
                <Th k="auto_generated">Auto-gen</Th>
                <Th k="model">Model</Th>
                <Th k="instrument">Instrument</Th>
                <Th k="direction">Direction</Th>
                <Th k="entry" num>Entry</Th>
                <Th k="entered">Entered</Th>
                <Th k="atm_strategy">ATM Strategy</Th>
                <Th k="risk_reward" num>R:R</Th>
                <Th k="contracts" num>Qty</Th>
                <Th k="outcome">Outcome</Th>
                <Th k="realized_pnl" num>P&L</Th>
                <Th k="time_in_trade" num>Time</Th>
                <Th k="auto_resolved">Auto-res</Th>
                <Th k="notes">Notes</Th>
              </tr>
            </thead>
            <tbody>
              {signals.map((s) => {
                const isSelected = selected.has(s.timestamp)
                return (
                  <tr key={s.timestamp}>
                    <td className="select-col">
                      <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={() => toggleOne(s.timestamp)}
                      />
                    </td>
                    <td title={tradeTs(s) !== s.timestamp ? `signal generated ${fmtTs(s.timestamp)}` : undefined}>
                      <Link to={`/signals/${encodeURIComponent(s.timestamp)}`}>
                        {fmtTs(tradeTs(s))}
                      </Link>
                    </td>
                    <td title={isAutoGenerated(s) ? 'Auto-generated by headless analyzer' : 'Manual capture (Ctrl+Shift+F)'}>
                      {isAutoGenerated(s) ? '✓' : <span className="subtle">—</span>}
                    </td>
                    <td title={s.provider ? `provider: ${s.provider}` : undefined}>
                      {s.model || <span className="subtle">—</span>}
                    </td>
                    <td>{s.proposal?.instrument || '—'}</td>
                    <td>{s.proposal?.direction || '—'}</td>
                    <td className="num">{fmtPrice(s.proposal?.entry, s.proposal?.instrument)}</td>
                    <td title={
                      s.entry_hit_ts
                        ? `Entry hit at ${new Date(s.entry_hit_ts).toLocaleString()}`
                        : 'Auto-resolved by the bot: hit / no_entry (after 4 h) / pending'
                    }>
                      {(() => {
                        const st = enteredState(s)
                        if (st === 'hit')      return <span className="entered-hit">✓ entered</span>
                        if (st === 'no_entry') return <span className="entered-no">no entry</span>
                        return <span className="subtle">pending</span>
                      })()}
                    </td>
                    <td title={
                      s.proposal?.atm_strategy === 'custom'
                        ? `Custom suggestion (not in your NT templates): stop=${s.proposal?.atm_stop_ticks ?? '?'}t target=${s.proposal?.atm_target_ticks ?? '?'}t`
                        : s.proposal?.atm_strategy
                          ? `stop=${s.proposal?.atm_stop_ticks ?? '?'}t target=${s.proposal?.atm_target_ticks ?? '?'}t`
                          : 'No ATM strategy on this signal (older record or LLM omitted)'
                    }>
                      {s.proposal?.atm_strategy === 'custom'
                        ? <span className="atm-custom">custom ({s.proposal?.atm_stop_ticks}t/{s.proposal?.atm_target_ticks}t)</span>
                        : s.proposal?.atm_strategy || <span className="subtle">—</span>}
                    </td>
                    <td className="num">{fmtRR(s.proposal?.risk_reward)}</td>
                    <td className="num" title="Contracts in the trade (ATM template total qty)">
                      {contractsOf(s) ?? <span className="subtle">—</span>}
                    </td>
                    <td title={s.outcome?.note ?? undefined}>
                      {s.outcome?.result
                        ? (s.outcome.auto_confirmed
                            ? <><span>{s.outcome.result}</span> <span className="subtle">(auto)</span></>
                            : s.outcome.result)
                        : <span className="subtle">—</span>}
                    </td>
                    <td
                      className={`num ${pnlCls(s.metrics?.realized_pnl ?? 0)}`}
                      title={s.metrics?.realized_pnl_source
                        ? `Source: ${s.metrics.realized_pnl_source}`
                        : 'No realized P&L on this signal'}
                    >
                      {typeof s.metrics?.realized_pnl === 'number'
                        ? fmtMoney(s.metrics.realized_pnl)
                        : <span className="subtle">—</span>}
                    </td>
                    <td className="num" title="Time in trade: entry to last leg exit">
                      {(() => {
                        const ms = timeInTradeMs(s)
                        return ms === null ? <span className="subtle">—</span> : fmtDuration(ms)
                      })()}
                    </td>
                    <td title={isAutoResolved(s) ? 'Outcome auto-resolved by feed.db walker' : 'Manually set or unresolved'}>
                      {isAutoResolved(s) ? '✓' : <span className="subtle">—</span>}
                    </td>
                    <td className="notes-cell" title={s.journal?.note ?? undefined}>
                      {s.journal?.note || <span className="subtle">—</span>}
                    </td>
                  </tr>
                )
              })}
              {signals.length === 0 && (
                <tr>
                  <td colSpan={17} className="subtle" style={{ textAlign: 'center', padding: '20px' }}>
                    No signals yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
    </>
  )
}

function SignalFilterBar({ filters, setFilters, instruments }: {
  filters:     SignalFilters
  setFilters:  (f: SignalFilters) => void
  instruments: string[]
}) {
  const active = filtersActive(filters)
  const toggleInstrument = (ins: string) => {
    const next = filters.instruments.includes(ins)
      ? filters.instruments.filter((x) => x !== ins)
      : [...filters.instruments, ins]
    setFilters({ ...filters, instruments: next })
  }
  const setDirection = (d: SignalFilters['direction']) =>
    setFilters({ ...filters, direction: filters.direction === d ? '' : d })

  return (
    <div className="signal-filter-bar">
      <div className="signal-filter-row">
        <span className="signal-filter-label">Instrument</span>
        {instruments.length === 0 ? (
          <span className="subtle">no signals yet</span>
        ) : (
          <div className="chip-row">
            {instruments.map((ins) => (
              <button
                key={ins}
                type="button"
                className={'chip' + (filters.instruments.includes(ins) ? ' on' : '')}
                onClick={() => toggleInstrument(ins)}
              >
                {ins}
              </button>
            ))}
          </div>
        )}
      </div>

      <div className="signal-filter-row">
        <span className="signal-filter-label">Direction</span>
        <div className="chip-row">
          {(['long', 'short', 'flat'] as const).map((d) => (
            <button
              key={d}
              type="button"
              className={'chip' + (filters.direction === d ? ' on' : '')}
              onClick={() => setDirection(d)}
            >
              {d}
            </button>
          ))}
        </div>
      </div>

      <div className="signal-filter-row">
        <span className="signal-filter-label">Trading day</span>
        <input
          type="date"
          value={filters.dayFrom}
          onChange={(e) => setFilters({ ...filters, dayFrom: e.target.value })}
          aria-label="From trading day"
        />
        <span className="subtle">to</span>
        <input
          type="date"
          value={filters.dayTo}
          onChange={(e) => setFilters({ ...filters, dayTo: e.target.value })}
          aria-label="To trading day"
        />
      </div>

      <div className="signal-filter-row">
        <span className="signal-filter-label">Date + time</span>
        <input
          type="datetime-local"
          value={filters.fromTs}
          onChange={(e) => setFilters({ ...filters, fromTs: e.target.value })}
          aria-label="From date and time"
        />
        <span className="subtle">to</span>
        <input
          type="datetime-local"
          value={filters.toTs}
          onChange={(e) => setFilters({ ...filters, toTs: e.target.value })}
          aria-label="To date and time"
        />
        {(filters.fromTs || filters.toTs) && (
          <button
            type="button"
            className="chip"
            onClick={() => setFilters({ ...filters, fromTs: '', toTs: '' })}
            aria-label="Clear date and time range"
          >
            clear
          </button>
        )}
      </div>

      {active && (
        <button
          type="button"
          className="signal-filter-clear"
          onClick={() => setFilters(EMPTY_FILTERS)}
        >
          Clear filters
        </button>
      )}
    </div>
  )
}
