import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate } from 'react-router-dom'
import { deleteJSON, fetchJSON, postJSON, type Signal, type SignalListResp } from '../api'
import { arrow, flip, sortBy, type Sort } from '../lib/sorting'

type SignalKey =
  | 'timestamp'
  | 'auto_generated'
  | 'instrument'
  | 'direction'
  | 'entry'
  | 'entered'
  | 'atm_strategy'
  | 'risk_reward'
  | 'confidence'
  | 'verdict'
  | 'outcome'
  | 'auto_resolved'

type EnteredState = 'hit' | 'no_entry' | 'pending'
const FOUR_HOURS_MS = 4 * 3600 * 1000

function enteredState(s: Signal): EnteredState {
  // Bot-side entry_resolver writes entry_triggered true/false within the 4h
  // window. While we're waiting on it (or pre-watcher signals), derive a
  // local 'pending' vs 'no_entry' fallback so the column still tells a
  // useful story before the bot catches up.
  if (s.entry_triggered === true) return 'hit'
  if (s.entry_triggered === false) return 'no_entry'
  // Implicit: not yet resolved by watcher. Check signal age.
  const t = Date.parse(s.timestamp)
  if (isNaN(t)) return 'pending'
  return (Date.now() - t) >= FOUR_HOURS_MS ? 'no_entry' : 'pending'
}

const isAutoGenerated = (s: Signal): boolean => s.trigger === 'headless'

const isAutoResolved = (s: Signal): boolean =>
  s.outcome?.result !== undefined &&
  s.outcome?.result !== null &&
  s.outcome_suggestion?.engine === 'resolver'

const accessor = (s: Signal, k: SignalKey): unknown => {
  switch (k) {
    case 'timestamp':      return s.timestamp
    case 'auto_generated': return isAutoGenerated(s)
    case 'instrument':     return s.proposal?.instrument
    case 'direction':      return s.proposal?.direction
    case 'entry':          return s.proposal?.entry
    case 'entered':        return enteredState(s)
    case 'atm_strategy':   return s.proposal?.atm_strategy ?? ''
    case 'risk_reward':    return s.proposal?.risk_reward
    case 'confidence':     return s.proposal?.confidence
    case 'verdict':        return s.journal?.verdict ?? null
    case 'outcome':        return s.outcome?.result ?? null
    case 'auto_resolved':  return isAutoResolved(s)
  }
}

const fmtTs = (ts: string) => ts.replace('T', ' ').slice(0, 19)
const fmtNum = (n: number | undefined, digits = 2) =>
  n === undefined || n === null ? '' : n.toFixed(digits)
// Compact R:R display. 1.0 -> "1:1", 2.5 -> "1:2.5", 10.0 -> "1:10".
// Avoids the wide '10.00' column that 1:10 strategies produced.
const fmtRR = (n: number | undefined): string => {
  if (n === undefined || n === null) return ''
  if (!isFinite(n) || n <= 0) return '—'
  return n >= 10 ? `1:${Math.round(n)}` : `1:${n.toFixed(1)}`
}

export function SignalAnalysisPage() {
  const [sort, setSort] = useState<Sort<SignalKey>>({ key: 'timestamp', dir: 'desc' })
  const [selected, setSelected] = useState<Set<string>>(new Set())
  const navigate = useNavigate()
  const qc = useQueryClient()

  const q = useQuery<SignalListResp>({
    queryKey: ['signals'],
    queryFn: () => fetchJSON<SignalListResp>('/api/signals'),
  })

  const capture = useMutation({
    mutationFn: () => postJSON<{ signal: Signal }>('/api/signals/capture'),
    onSuccess: (data) => {
      qc.invalidateQueries({ queryKey: ['signals'] })
      if (data?.signal?.timestamp) {
        navigate(`/signals/${encodeURIComponent(data.signal.timestamp)}`)
      }
    },
  })

  const bulkDelete = useMutation({
    mutationFn: async (timestamps: string[]) => {
      await Promise.all(timestamps.map((ts) =>
        deleteJSON(`/api/signals/${encodeURIComponent(ts)}`),
      ))
    },
    onSuccess: () => {
      setSelected(new Set())
      qc.invalidateQueries({ queryKey: ['signals'] })
    },
  })

  const signals = useMemo(() => {
    if (!q.data) return []
    return sortBy(q.data.signals, sort, accessor)
  }, [q.data, sort])

  // Today's-signals KPI: derive locally from the signal list so we don't
  // need a separate API. "Today" is the same local-date semantics the
  // server uses in home.py's today_pnl computation.
  const todayKpi = useMemo(() => {
    const today = new Date().toISOString().slice(0, 10)
    const todays = (q.data?.signals ?? []).filter(
      (s) => (s.timestamp || '').slice(0, 10) === today,
    )
    let pnl = 0
    let wins = 0
    let losses = 0
    const instruments = new Set<string>()
    for (const s of todays) {
      const p = s.metrics?.realized_pnl
      if (typeof p === 'number') {
        pnl += p
        if (p > 0) wins++
        else if (p < 0) losses++
      }
      const ins = s.proposal?.instrument
      if (ins) instruments.add(ins)
    }
    return {
      date:        today,
      count:       todays.length,
      pnl:         Math.round(pnl * 100) / 100,
      wins,
      losses,
      instruments: Array.from(instruments).sort(),
    }
  }, [q.data])

  const allVisibleTs = signals.map((s) => s.timestamp)
  const allSelected = allVisibleTs.length > 0 && allVisibleTs.every((ts) => selected.has(ts))

  const toggleOne = (ts: string) => {
    const next = new Set(selected)
    if (next.has(ts)) next.delete(ts)
    else next.add(ts)
    setSelected(next)
  }
  const toggleAll = () => {
    if (allSelected) setSelected(new Set())
    else setSelected(new Set(allVisibleTs))
  }
  const onBulkDelete = () => {
    if (selected.size === 0) return
    if (confirm(`Delete ${selected.size} signal(s)? They'll be hidden from the dashboard. (Recoverable by editing signals.jsonl.)`)) {
      bulkDelete.mutate(Array.from(selected))
    }
  }

  const Th = ({ k, children, num }: { k: SignalKey; children: React.ReactNode; num?: boolean }) => (
    <th className={num ? 'num' : ''} onClick={() => setSort(flip(sort, k))}>
      {children}
      {arrow(sort, k)}
    </th>
  )

  const fmtMoney = (n: number) =>
    `$${n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
  const pnlCls = (n: number) => (n > 0 ? 'pnl-pos' : n < 0 ? 'pnl-neg' : '')

  return (
    <>
      <div className="card">
        <h2>Today's Signals · {todayKpi.date}</h2>
        <div className="big">
          <span className={pnlCls(todayKpi.pnl)}>{fmtMoney(todayKpi.pnl)}</span>
          <span className="big-sub"> realized (signals)</span>
        </div>
        <div className="kv"><span>Signals captured</span><span>{todayKpi.count}</span></div>
        <div className="kv"><span>Resolved (W/L)</span><span>{todayKpi.wins}W / {todayKpi.losses}L</span></div>
        <div className="kv"><span>Instruments</span><span>{todayKpi.instruments.join(', ') || '—'}</span></div>
      </div>
    <div className="card">
      <div className="signals-header">
        <h2>Signal Analysis {q.data && `(${q.data.count})`}</h2>
        <button
          type="button"
          className="primary capture-btn"
          onClick={() => capture.mutate()}
          disabled={capture.isPending}
          title="Open the Windows Snipping overlay; drag a rectangle on a NinjaTrader chart"
        >
          {capture.isPending ? 'Snipping… drag a rectangle on your chart' : 'Snip & Analyze'}
        </button>
      </div>
      {capture.error && (
        <div className="error" style={{ marginBottom: 12 }}>
          {String(capture.error)}
        </div>
      )}
      {selected.size > 0 && (
        <div className="bulk-bar">
          <span>{selected.size} selected</span>
          <button type="button" onClick={() => setSelected(new Set())}>Clear</button>
          <button
            type="button"
            className="danger"
            onClick={onBulkDelete}
            disabled={bulkDelete.isPending}
          >
            {bulkDelete.isPending ? 'Deleting…' : `Delete ${selected.size} signal(s)`}
          </button>
          {bulkDelete.error && <span className="error"> {String(bulkDelete.error)}</span>}
        </div>
      )}
      {q.isLoading ? (
        <div>Loading…</div>
      ) : q.error ? (
        <div className="error">{String(q.error)}</div>
      ) : (
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th className="select-col">
                  <input
                    type="checkbox"
                    checked={allSelected}
                    onChange={toggleAll}
                    title={allSelected ? 'Deselect all' : 'Select all'}
                  />
                </th>
                <Th k="timestamp">Timestamp</Th>
                <Th k="auto_generated">Auto-gen</Th>
                <Th k="instrument">Instrument</Th>
                <Th k="direction">Direction</Th>
                <Th k="entry" num>Entry</Th>
                <Th k="entered">Entered</Th>
                <Th k="atm_strategy">ATM Strategy</Th>
                <Th k="risk_reward" num>R:R</Th>
                <Th k="confidence" num>Conf</Th>
                <Th k="verdict">Verdict</Th>
                <Th k="outcome">Outcome</Th>
                <Th k="auto_resolved">Auto-res</Th>
              </tr>
            </thead>
            <tbody>
              {signals.map((s) => {
                const sugPending =
                  !!s.outcome_suggestion && !s.outcome_suggestion_dismissed
                const isSelected = selected.has(s.timestamp)
                return (
                  <tr key={s.timestamp} className={sugPending ? 'pending-suggestion' : ''}>
                    <td className="select-col">
                      <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={() => toggleOne(s.timestamp)}
                      />
                    </td>
                    <td>
                      <Link to={`/signals/${encodeURIComponent(s.timestamp)}`}>
                        {fmtTs(s.timestamp)}
                      </Link>
                    </td>
                    <td title={isAutoGenerated(s) ? 'Auto-generated by headless analyzer' : 'Manual capture (Ctrl+Shift+F)'}>
                      {isAutoGenerated(s) ? '✓' : <span className="subtle">—</span>}
                    </td>
                    <td>{s.proposal?.instrument || '—'}</td>
                    <td>{s.proposal?.direction || '—'}</td>
                    <td className="num">{fmtNum(s.proposal?.entry, 4)}</td>
                    <td title={
                      s.entry_hit_ts
                        ? `Entry hit at ${new Date(s.entry_hit_ts).toLocaleString()}`
                        : 'Auto-resolved by the bot: hit / no_entry (after 4 h) / pending'
                    }>
                      {(() => {
                        const st = enteredState(s)
                        if (st === 'hit')      return <span className="entered-hit">✓ entered</span>
                        if (st === 'no_entry') return <span className="entered-no">no entry</span>
                        return <span className="subtle">pending</span>
                      })()}
                    </td>
                    <td title={
                      s.proposal?.atm_strategy === 'custom'
                        ? `Custom suggestion (not in your NT templates): stop=${s.proposal?.atm_stop_ticks ?? '?'}t target=${s.proposal?.atm_target_ticks ?? '?'}t`
                        : s.proposal?.atm_strategy
                          ? `stop=${s.proposal?.atm_stop_ticks ?? '?'}t target=${s.proposal?.atm_target_ticks ?? '?'}t`
                          : 'No ATM strategy on this signal (older record or LLM omitted)'
                    }>
                      {s.proposal?.atm_strategy === 'custom'
                        ? <span className="atm-custom">custom ({s.proposal?.atm_stop_ticks}t/{s.proposal?.atm_target_ticks}t)</span>
                        : s.proposal?.atm_strategy || <span className="subtle">—</span>}
                    </td>
                    <td className="num">{fmtRR(s.proposal?.risk_reward)}</td>
                    <td className="num">
                      {s.proposal?.confidence !== undefined
                        ? `${(s.proposal.confidence * 100).toFixed(0)}%`
                        : ''}
                    </td>
                    <td>{s.journal?.verdict || <span className="subtle">—</span>}</td>
                    <td title={s.outcome?.note ?? undefined}>
                      {s.outcome?.result
                        ? (s.outcome.auto_confirmed
                            ? <><span>{s.outcome.result}</span> <span className="subtle">(auto)</span></>
                            : s.outcome.result)
                        : <span className="subtle">—</span>}
                    </td>
                    <td title={isAutoResolved(s) ? 'Outcome auto-resolved by feed.db walker' : 'Manually set or unresolved'}>
                      {isAutoResolved(s) ? '✓' : <span className="subtle">—</span>}
                    </td>
                  </tr>
                )
              })}
              {signals.length === 0 && (
                <tr>
                  <td colSpan={14} className="subtle" style={{ textAlign: 'center', padding: '20px' }}>
                    No signals yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
    </>
  )
}
